### PR TITLE
Upgrade nostr-tools to v1.7.4

### PR DESCRIPTION
**Pull request by alexgleason**
The latest nostr-tools includes important fixes for Deno which also affects this package.

### CODE REVIEW

**Review by adamritter — APPROVED** [review]

**Comment by adamritter** [comment]
I had to revert it because it breaks the tests. At the same time of course we should upgrade nostr-tools

**Comment by adamritter** [comment]
Merged again with ignoring type arrors about sig missing (which can be optionally deleted)

**Comment by adamritter** [comment]
Also I released nostr-relaypool 0.5.14 with the change

**Comment by alexgleason** [comment]
Thank you!

**Pull request merged**
