### PR TITLE
relay-pool: add support for nip42 authentication

### PR DESCRIPTION
**Pull request by npub1zenn0**
Fixes https://github.com/adamritter/nostr-relaypool-ts/issues/39

### CODE REVIEW

**Comment by adamritter** [comment]
Thanks, looks great!

I published 0.6.18, can you check if it works?

**Comment by npub1zenn0** [comment]
Will do.

**Comment by npub1zenn0** [comment]
Seems good.

**Comment by adamritter** [comment]
great, I added you as member, if you want I give you write access.

Although from what I see you're bounty hunter :)

**Comment by npub1zenn0** [comment]
> Although from what I see you're bounty hunter :)

hehee, you got that right

**Comment by adamritter** [comment]
Sure, I can add some smaller relaypool bounties

**Comment by npub1zenn0** [comment]
Sounds good to me. You should list em on nostr, via nostrbounties.com (only one I know of, for this)

**Comment by adamritter** [comment]
https://nostrbounties.com/b/naddr1qq9rzd3cxgcnzdf5xc6sygrw8agkvnseuzpd75shl4zf9wukjp6qtg9jwq5xw8wh72tmdzrq3spsgqqqw4rstz66a2

**Comment by npub1zenn0** [comment]
Cheers, may get to it later.

**Comment by adamritter** [comment]
sure bounstr is the old one, you should check those bounties out as
well (though there's overlap), actually I added some nostrbounties
bountes as well for Diego some time ago :)

**Comment by adamritter** [comment]
bounstr has much bigger bounties though, like Telegram port, I would
hunt them (10million sats) in your place :D

**Comment by npub1zenn0** [comment]
Oh yeah I knew of bountsr, am actually doing a stack of bounties from there now, some good overlap.

**Pull request merged**
