### PR TITLE
Set kind to 2 or update Event type

### PR DESCRIPTION
**Pull request by agustinkassis**

### CODE REVIEW

**Comment by adamritter** [comment]
Hi Augustin,

I'm not sure what this change is about, but kind 2 is generally not used by relays, because it contains only 1 relay. 10003 is a ,,hack'' on wss://us.rbr.bio and wss://eu.rbr.bio that serves write relays until 10002 is used everywhere, similarly to Pablo's server (purple nostr or something like that).

I'm planning to talk to him about using the same kind for this purpose, and of course transitioning to 10002 should be a priority.

**Comment by moogmodular** [comment]
Cant build because of this.

image

**Comment by adamritter** [comment]
:( I understand now

Does // @ts-ignore help?

**Comment by moogmodular** [comment]
> :( I understand now Does // @ts-ignore help?

You mean by monkey patching? Im using it as a library. `skipLibCheck` and excluding `node_modules` didn't help either. Rolling back to `0.6.7` for now.

**Comment by adamritter** [comment]
No, I'll merge it of course and release.  Meanwhile of course you can use
yarn link if you use yarn anyways :)

**Comment by adamritter** [comment]
I added @ts-ignore and released a new npm.

Can you please verify that it builds for you?

**Comment by agustinkassis** [comment]
Im sorry, I included the lib dir in the pull request, as I had in my own repo.

nostr-tools should include that kind.

**Comment by moogmodular** [comment]
> Can you please verify that it builds for you?

`0.6.16` builds now, thanks

**Pull request closed without merging**
